# KixsSimpleBackpacks config
backpack:
  material: CHEST
  rows: 2
  gui-title: "Backpack"
  name:
    regular: "&eBackpack"
    renamed: "&eBackpack: '&f{CUSTOM_NAME}&e'"
  lore:
    new:
      - " "
      - "&bBrand new, open me!"
      - " "
    empty:
      - " "
      - "&6{SLOTS_IN_USE}/{MAX_SLOTS} &fslots in use"
      - " "
    storing:
      - " "
      - "&6{SLOTS_IN_USE}/{MAX_SLOTS} &fslots in use"
      - " "
      - "{CONTENTS_PREVIEW}"
    contents-preview: " &f- &7&o{ITEM_AMOUNT}x &f&o{ITEM_NAME}"
    preview-overflow:
      - " "
      - " &f&oand &7{REMAINING_CONTENTS_SLOT_COUNT} &f&omore..."
      - " "
    preview-slots-size: 5