# KixsSimpleBackpacks config
# Colorcode and hex (for 1.16+) support: & for colorcodes, &# for hex
backpack:
  recipe:
    shape:
      top: "LLL"
      mid: "ICI"
      btm: "LLL"
    key:
      L:
        - "LEATHER"
      I:
        - "IRON_INGOT"
      C:
        - "CHEST"
  material: CHEST
  rows: 2
  gui-title: "Backpack"
  name:
    regular: "&eBackpack"
    renamed: "&eBackpack: '&f{CUSTOM_NAME}&e'"
    unopened: "&eNew Backpack"
  lore:
    new:
      - " "
      - "&bBrand new, &b&nright click&b to unbox!"
      - " "
    empty:
      - " "
      - "&6{SLOTS_IN_USE}/{MAX_SLOTS} &fslots in use"
      - " "
    storing:
      - " "
      - "&6{SLOTS_IN_USE}/{MAX_SLOTS} &fslots in use"
      - " "
      - "{CONTENTS_PREVIEW}"
    contents-preview: " &f- &7&o{ITEM_AMOUNT}x &f&o{ITEM_NAME}"
    preview-overflow:
      - " "
      - " &f&oand &7{REMAINING_CONTENTS_SLOT_COUNT} &f&omore..."
      - " "
    preview-slots-size: 5
  messages:
    unboxed: "&7Backpack unboxed! &bRight click&7 it to open!"